services:
  web:
    build: .
    command: flask run --host 0.0.0.0 --port 8000 --debug
    ports:
      - 8001:8000
    depends_on:
      - db
    environment:
      - FLASK_APP=app
      - FLASK_END=development
    volumes:
      - .:/usr/src/app

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: transformers_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
